name: Compilar APK con Python y Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update

          sudo apt-get install -y
            git 
            zip 
            unzip 
            autoconf 
            automake 
            libtool 
            pkg-config 
            zlib1g-dev 
            libncurses5-dev 
            libncursesw5-dev 
            libtinfo6 
            cmake 
            libffi-dev 
            libssl-dev 
            gettext

      - name: Instalar Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install "buildozer"
          python -m pip install "Cython==0.29.34"

      - name: Verificar entorno
        run: |
          python --version
          java -version
          buildozer --version

      - name: Limpiar compilaciones anteriores
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Compilar APK
        run: |
          buildozer -v android debug

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: app-release-android
          path: bin/*.apk
          if-no-files-found: error
